version: "3"

services:
  web:
    build:
      context: ./
      dockerfile: ./Waffler.Web/Dockerfile
      args:
        build_id: 1
    image: waffler-web
    depends_on:
      - api
    ports:
      - 8088:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - API__BaseUrl=http://localhost:5005/
      - API__Version=v1
    volumes:
      - ./https:/https:ro
  api:
    build:
      context: ./
      dockerfile: ./Waffler.API/Dockerfile
      args:
        build_id: 1
    image: waffler-api
    depends_on:
      - db
    ports:
      - 5005:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - Database__Server=db
      - Database__Catalog=Waffler
      - Database__Credentials=User ID=sa;Password=pAssword1234
      - Database__Service__IndexFragmentationAnalasys__TriggerTime=02:00
      - Profile__DefaultCandleStickSyncOffsetDays=90
      - Bitpanda__BaseUri=https://api.exchange.bitpanda.com/public/v1/
      - Bitpanda__OrderFeature__Buy=true
      - Bitpanda__OrderFeature__Sell=false
    volumes:
      - ./https:/https:ro
  db:
    build:
      context: ./
      dockerfile: ./Waffler.Data/Dockerfile
      args:
        RS_DATABASE_NAME: Waffler
    image: waffler-db
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: pAssword1234
      MSSQL_PID: Developer
      MSSQL_COLLATION: SQL_Latin1_General_CP1_CI_AS
    ports:
      - 1433:1433