version: "3"



services:
  web:
    image: ghcr.io/citou-ab/waffler-web
    depends_on:
      - api
    ports:
      - 8080:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - API__BaseUrl=http://localhost:5005/
      - API__Version=v1
    volumes:
      - ./https:/https:ro
  api:
    image: ghcr.io/citou-ab/waffler-api
    depends_on:
      - db
    ports:
      - 5005:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - Database__ConnectionString=Server=db;Initial Catalog=Waffler;User ID=sa;Password=pAssword1234
    volumes:
      - ./https:/https:ro
  db:
    image: ghcr.io/citou-ab/waffler-db
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: pAssword1234
      MSSQL_PID: Developer
      MSSQL_COLLATION: SQL_Latin1_General_CP1_CI_AS
    ports:
      - 1433:1433