version: "3"

services:
  web:
    image: ghcr.io/citouhub/waffler-web-arm64:latest
    depends_on:
      - api
    ports:
      - 8088:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - API__BaseUrl=http://waffler.local:5005/
      - API__Version=v1
    volumes:
      - ./https:/https:ro
  api:
    image: ghcr.io/citouhub/waffler-api-arm64:latest
    depends_on:
      - db
    ports:
      - 5005:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - Database__Server=db
      - Database__Catalog=Waffler
      - Database__Credentials=User ID=sa;Password=pAssword1234
      - Database__Service__IndexFragmentationAnalasys__TriggerTime=02:00
      - Profile__DefaultCandleStickSyncOffsetDays=90
      - Profile__SessionExpirationMinutes=1200
      - Bitpanda__BaseUri=https://api.exchange.bitpanda.com/public/v1/
      - Bitpanda__OrderFeature__Buy=true
      - Bitpanda__OrderFeature__Sell=false
      - Bitpanda__OrderFeature__MinimumBuyBalance=20
      - Bitpanda__OrderFeature__MinimumSellBalance=0.0005
      - Github__BaseUri=https://api.github.com/
      - Github__Owner=CitouHub
    volumes:
      - ./https:/https:ro
  db:
    image: mcr.microsoft.com/azure-sql-edge:1.0.4
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: pAssword1234
      MSSQL_PID: Developer
      MSSQL_COLLATION: SQL_Latin1_General_CP1_CI_AS
    ports:
      - 1433