FROM mcr.microsoft.com/azure-sql-edge:latest
EXPOSE 1433

ARG RS_DATABASE_NAME=Waffler
ENV RS_DATABASE_NAME $RS_DATABASE_NAME

LABEL org.opencontainers.image.source="https://github.com/CitouHub/waffler"