name: Waffler build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  REGISTRY: ghcr.io
  USERNAME: CitouHub
  PASSWORD: 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
  DB_IMAGE_NAME: waffler-db
  API_IMAGE_NAME: waffler-api
  WEB_IMAGE_NAME: waffler-web

jobs:
  build_push_db:
    name: Build and push DB image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ env.USERNAME }}
        password: ${{ env.PASSWORD }}

    - name: Build and tag image for DB
      run: docker build --tag ghcr.io/citou-ab/$DB_IMAGE_NAME:latest . --file Waffler.Data/Dockerfile

    - name: Push image for DB
      run: docker push --all-tags ghcr.io/citou-ab/$DB_IMAGE_NAME

  build_push_api:
    name: Build and push API image
    runs-on: buster-slim
    strategy:
      matrix:
        arch: [arm64]
        container: [debian_10]
    steps:
    - uses: actions/checkout@v2
    
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ env.USERNAME }}
        password: ${{ env.PASSWORD }}

    - name: Build and tag image for API
      run: docker build --tag ghcr.io/citou-ab/$API_IMAGE_NAME:latest . --file Waffler.API/Dockerfile

    - name: Push image for DB
      run: docker push --all-tags ghcr.io/citou-ab/$API_IMAGE_NAME

  build_push_web:
    name: Build and push Web image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ env.USERNAME }}
        password: ${{ env.PASSWORD }}

    - name: Build and tag image for Web
      run: docker build --tag ghcr.io/citou-ab/$WEB_IMAGE_NAME:latest . --file Waffler.Web/Dockerfile

    - name: Push image for Web
      run: docker push --all-tags ghcr.io/citou-ab/$WEB_IMAGE_NAME
