name: Waffler API

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: waffler-api

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: CitouHub
        password: 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

    - name: Build and tag image for DB with `${{ env.RELEASE_TAG_INPUT }}`
      run: docker build --tag ghcr.io/waffler-api:latest .

    - name: Push image for DB
      run: docker push --all-tags ghcr.io/waffler-api
