name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the api image
      run: docker build ./Waffler.API --file Waffler.API/Dockerfile --tag waffler-api:$(date +%s)
